### ISSUE TITLE
Support for ancillary package managers

### ISSUE THREAD

**Issue by cbailes** [emilengler/sysget#10]
What about ancillary package managers, such as Docker, npm, and pip?

**Comment by emilengler** [comment]
pip is a great idea.
I'm not very sure about npm it is a global package manager of course but it can also be used to install inside of a resporitory. In this case npm would only get global support.
I'm not very sure about docker at the moment

**Comment by cvengler** [comment]
Hello cbailes, thanks for your suggestion.
The problems with pip are the difference between pip and pip3 and package upgrading because pip does not support this by default maybe it will be implemented in future.
However npm is a good idea.
I'm not very sure about docker in the moment.

**Comment by cvengler** [comment]
npm is added https://github.com/emilengler/sysget/commit/2eda6f5ba5a9e66ff36b43d4f6216629dbcfd344
