### ISSUE TITLE
maybe it's better to define the interface?

### ISSUE THREAD

**Issue by qiweiye** [emilengler/sysget#20]
I like this project's idea. 

But after looking the code, I feel that maybe it's better to define an interface(contains all virtual methods, such as install, remove, search), and then each package manager to implement this interface.

So, only need to compare the package name once, and choose the right inherited class, and call the related method.

**Comment by cvengler** [comment]
Good idea I already thought about it.
Currently we have the help method which displays the functions.
We truly need auto completion

**Comment by cvengler** [comment]
Thanks for your idea!
