### ISSUE TITLE
Suggest changing the default path of configuration

### ISSUE THREAD

**Issue by owlinux1000** [emilengler/sysget#23]
This project is a great idea! And, Thanks for merged my PR!

By the way, I should change the default path of configuration.
For example, OS X prohibits creating any directories and files such as ```/usr/bin``` .

How do you think about the default path of configuration?
My idea are ```$HOME/.sysget``` and ```$HOME/.config/sysget```.

**Comment by cvengler** [comment]
Good idea, this would also gives the user the ability to change packages managers without the need of root privileges. This would make sense for snap because you don't need to be root to install a snap.

**Comment by emilengler** [comment]
PS: I prefer `$HOME/.sysget` instead of `$HOME/.config/sysget`.

**Comment by emilengler** [comment]
But one second, what is if the user executes sysget as root which is in 99% the case ?
It would use `/root/.sysget/config` aren't

**Comment by owlinux1000** [comment]
If we change the path to ```$HOME/.sysget```, need to run as ```sudo -E sysget```.
I think this is not good.
Then ```/etc/sysget```  is better than ```/usr/share```.
Anyways, OS X usually can't write any files to ```/usr/bin```, ```/usr/share``` and so on, we need to change the path.

**Comment by cvengler** [comment]
I agree the code should work as fine on macOS as it does on Linux so we should use /etc/sysget.
Can you change this and do a Pull-Request ? I will merge then.
I currently have issues with my Computer (especially my Desktop Environment which is completely broken) which I will fix tomorrow so I cannot do it on my own at the moment.

Thank you a lot for contributing.
Greetings Emil

**Comment by owlinux1000** [comment]
I see. I'll do pull-request that the path is replaced with /etc/sysget later !

By the way, make install uses /usr/bin, this is same issue on OS X. However its my idea  still is none, sorry.

**Comment by owlinux1000** [comment]
Thanks for the merge!
