### ISSUE TITLE
question: front-end adapters for various package managers?

### ISSUE THREAD

**Issue by Osndok** [emilengler/sysget#26]
Greetings.

I only now stumbled upon sysget, and was wondering if you would be interested in adding some complementary functionality to your project, that would effectively make sysget map "any-to-any" package manager.

What I had in mind is a series of simple shell scripts, and that a packager could just remove/ignore any that conflict with the system packager.

For example, the ```apt-get``` shell script might initially be as simple as:
```
#!/bin/bash
export SYSGET_NAMESPACE=apt
exec sysget "$@"
```

...and since ```yum``` & ```dnf``` automatically fetch metadata updates, their scripts might look more like:
```
#!/bin/bash
export SYSGET_NAMESPACE=fedora

case "$1" in
    install)
        sysget update
        shift
        exec sysget install "$@"
        ;;
    update)
        sysget update
        shift
        exec sysget upgrade "$@"
        ;;
    ...
esac
```
Note that the environment variables are to aid in possible future build-out along #5.

Would such scripts be a welcome addition to your project? or do you think they should be a separate-but-complementary project?

**Comment by cvengler** [comment]
It sounds great.
However I still don't get what you mean by

> conflict with the system packager

Can you explain it deeper ?
Thank you for contributing to sysget.
Greetings Emil

**Comment by Osndok** [comment]
WRT "remove any that conflict with the system packager", I just mean that sysget could have a **full** set of front-ends (apt-get, yum, dnf, zypper, etc), and whoever packages it (say, for a fedora rpm) could just remove the scripts with the same name as the native platform (yum & dnf, in this example).

**Comment by cvengler** [comment]
Your idea sounds interesting.
If you could a technical proposal I would take a look at it.
Thank you for contributing to sysget.
Greetings and best wishes Emil
