### ISSUE TITLE
Adjustment to sources.list.d file for Ubuntu Linux

### ISSUE THREAD

**Issue by TimothyDJones** [emilengler/sysget#27]
Great tool!

Just a quick note that I had to make an adjustment to the command in the installation instructions for Ubuntu Linux (18.04 in my case) for creating the repository file in /etc/apt/sources.list.d/:
```bash
echo "deb [arch=all] https://apt.emilengler.com/ stable main" | sudo tee /etc/apt/sources.list.d/emilengler.list
```

**Comment by cvengler** [comment]
Thank you!
I already know that it prints an error message when doing an update of the package list.
I will update the release page.
Thank you a lot!

**Comment by loungnlizard** [comment]
Timothy I tried to  install sysget on my Ubuntu 18.04 but failed. Did you use apt install and add  the location
for source file to sources list. Or did you use wget? Any tip would be appreciated.

**Comment by cvengler** [comment]
To be honest I haven't tried @TimothyDJones script yet because I wasn't at home there.
Let me do this now

**Comment by cvengler** [comment]
@loungnlizard We are creating a file called emilengler.list inside the sources.list.d folder.
Be sure to have the signing-key on your machine.
If this does not work try the legacy script:
`sudo wget -qO - https://apt.emilengler.com/signkey.asc | sudo apt-key add && sudo echo "deb https://apt.emilengler.com/ stable main" > /etc/apt/sources.list.d/emilengler.list && sudo apt update && sudo apt install sysget`

**Comment by cvengler** [comment]
FYI: I'm currently doing maintenance on the repo. I will post when I'm done

**Comment by cvengler** [comment]
Ok, I'm done with the maintenance.
The updated script is on the release page.
I have added amd64 and i386 as supported architectures.
However sysget will remain CrossArch which means that the arch is "all"

**Comment by cvengler** [comment]
@loungnlizard Does it work with this script now ?
`sudo wget -qO - https://apt.emilengler.com/signkey.asc | sudo apt-key add && sudo echo "deb https://apt.emilengler.com/ stable main" > /etc/apt/sources.list.d/emilengler.list && sudo apt update && sudo apt install sysget`

**Comment by cvengler** [comment]
Ok think this subject is over. I will close.
Feel free to respond at any time

**Comment by TimothyDJones** [comment]
Sorry for the late reply...  

Here are the commands that I used to install in Ubuntu 18.04/18.10:
```bash
sudo wget -qO - https://apt.emilengler.com/signkey.asc | sudo apt-key add
echo "deb [arch=all] https://apt.emilengler.com/ stable main" | sudo tee /etc/apt/sources.list.d/emilengler.list
sudo apt update 
sudo apt install -y sysget
```

**Comment by cvengler** [comment]
Sorry for my late reply too...
So does it work ?
@loungnlizard had problems with it so I replaced it with the old legacy script.

**Comment by loungnlizard** [comment]
@emilengler Yes it all worked, thank you and @TimothyDJones for the help. Will test out sysget on my Vbox install of Ubuntu 18.04 to reduce some of the bloat.

**Comment by cvengler** [comment]
Good look :+1: 
FYI: Yesterday I've added bash autocompletion, if you want to use it you need to compile and install it via the makefile until sysget 2.1 is out.

I think we are done here :smile:
