### ISSUE TITLE
Feature Request: Ansible Module

### ISSUE THREAD

**Issue by pinpox** [emilengler/sysget#3]
Hi,

this would be great as an ansible module to be able to automatically install packages on any system

**Comment by cvengler** [comment]
Hi, thank you for your feature request.
Can you please describe what an ansible module is ?
I don't get the advantage

**Comment by pinpox** [comment]
Well ansible (https://www.ansible.com/) is a system that automates software provisioning, configuration management, and application deployment.

In practice it is often used for example to automate the installation of packages on multiple servers. (You basically define what packages have to be installed on what system). For that ansible uses modules to communicate to package managers (in this example. Note: ansible can do a lot of other things apart from installing packages) 

Writing an ansible module is not very complicated, it's mainly a python script.
For example here is the module ansible uses to interact with pacman on arch linux:
https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/pacman.py
and you use it like this:
https://docs.ansible.com/ansible/latest/modules/pacman_module.html

The "problem" with ansible is that each module only works for one package manager. So, if you want to administer multiple servers with different OSs you have to specify the packages for each separately.

Having an sysget ansible module would make things very easy, as it could be used for all the supported systems. Since ansible is a very established project with a lot of users this could boost the usage/popularity of your sysget project.

Of course, this is just a well-meant suggestion. Creating an ansible module woud be separate repository, so no need to change sysget in any way probably, it would be just an **addition** that would make using sysget very attractive for some ansible users.

Cheers!

**Comment by pinpox** [comment]
Sorry for double commenting:
I just saw, there already is a generic package manager in ansible:
https://docs.ansible.com/ansible/2.5/modules/package_module.html
I don't know what managers are supported besides apt and yum. Maybe your project can improve on that

**Comment by cvengler** [comment]
Thanks for your detailed explanitation.
I looked at this project.
It would be a nice addition but only in a seperate repo because sysget should be KISS.
However thank you a lot :)
