### ISSUE TITLE
overview mode?

### ISSUE THREAD

**Issue by alexmyczko** [emilengler/sysget#31]
do you have an overview mode?
http://aiei.ch/linux/sw

**Comment by cvengler** [comment]
Nope not yet.
Can you explain what do you mean by that ?

**Comment by alexmyczko** [comment]
sw gives an overview of installed packages of following package managers: dpkg, rpm, snap, spack, 0install, flatpak, opam, cpan, pip2, pip3

**Comment by cvengler** [comment]
Sounds nice.
I already thought about adding something like:
`sysget list`
However I haven't added it yet because not every package manager supports something like this.
I will add it to my TODO-List.

**Comment by cvengler** [comment]
I think I can close this now.
Please reply if you have anything to add :-)
