### ISSUE TITLE
Automate operations

### ISSUE THREAD

**Issue by andrei-pavel** [emilengler/sysget#40]
I would find it extremely useful if sysget could install a package or do other operations regardless of which package manager is chosen for the job. Order of package managers is arbitrary and can be changed by user through configuration. Operation is stopped on the first package manager that succeeds.

e.g.
```
$ sysget --auto --install <package>
Not found for apt...
Installation failed for snap...
Installed successfully for flatpak.
```

Subsequent removal of package would also be correct in that flatpak would be chosen after the same sequence would be tried.

Would you accept a complete pull request on this?

**Comment by cvengler** [comment]
> Would you accept a complete pull request on this?

Sure I like it!
However it would need to "move" snap and fltapak out of the PM class probably, or they need to be marked as "special" package managers.
