### ISSUE TITLE
Feature Request: Add this to the AUR (Arch User Repository)

### ISSUE THREAD

**Issue by CMiksche** [emilengler/sysget#41]
The current installation progress takes some manual steps.

It would be more comfortable and would reach more users if this package could be installed with common package managers.
I think that the Arch User Repository (https://aur.archlinux.org/) would be a good first target to deploy this package to. 
Why? Because the AUR has low barriers for adding packages, a chance to get moved into the official sources and a good reach of users.

There are several ways for Arch Linux Users to access AUR packages. For example, Manjaro Linux Users can simply install package from the AUR with the standard package manager (pamac).

If the package gets popular in the AUR, there is also a chance that it gets moved into the official arch linux repositories.

See https://wiki.archlinux.org/index.php/Arch_User_Repository#Submitting_packages for more information about submitting.

**Comment by cvengler** [comment]
I already thought about adding sysget to some repos. I already requested it for Solus. However I mostly get the answer: "Just use pacman --help" or whatever else package manager. Also it would need maintenance. You and everyone else has green light to bring and maintain this software into any repo :)

**Comment by CMiksche** [comment]
Okay. I may look after getting this in the AUR.
