### ISSUE TITLE
Why are only package managers mapped, but not package names?

### ISSUE THREAD

**Issue by cookiengineer** [emilengler/sysget#5]
First off: I really like the underlying idea of the `sysget` project. In it's current state though I don't think it is really helpful at all, as most package names across distributions or operating systems are named differently, depending on how carzy the package maintainers are in their own philosophical beliefs.

For example: `gsed`, `gnu-sed` or `sed`. Another example `binutils`, `arm-none-linux-eabi-binutils` or `arm-linux-gnueabihf-binutils` and `arm-none-eabi-binutils`.

I mean, as a user: If I would switch to `sysget` there would be no point in maintaining an own list of packages, as it would most likely fail 99% of the time to install a single package of that list; and the point of using sysget itself is not reasonable anymore as I would have to detect the operating system or distribution anyways - to map the package names correctly.

I'm not sure whether this issue should be treated a feature request or so, but I hope I could describe the issue reasonably. Usually, when I try to almost-automatically map the package names for a specific distribution, I am using the very good `pkgs` search / API: https://pkgs.org/download/binutils

Maybe it makes sense to integrate their API so that people can use the same package names across multiple distributions?

An example of how usually package names across distributions look like, they are usually hard work as some packages here and there are not available and the package manager always fails when a single one is not available with the exact matching name: [example do-install.sh](https://github.com/Artificial-Engineering/lycheejs/blob/development/bin/maintenance/do-install.sh#L175)

**Comment by ghost** [comment]
hey, im not a developer but a friend, so ill answer this.
Do you mean the ability to choose from a list of packages, like how `aptitude` lets you?

**Comment by cvengler** [comment]
Hello cookieengineer
Sorry that it took so much time to answer this question for you.
It would make sense to implement this API.
However it would be better to implement it as an optional feature.
For example you could do
`sysget install -g git`
to search via the API for git in your repos.
I did not found an API reference on this site.
Can you please provide more informations about the API ?

**Comment by cookiengineer** [comment]
@saderror256 Yes, in a manner of speaking - but with the idea of automation in mind. So, something like `sysget install --fuzzy "binutils arm"` that would resolve the different package names automagically would be perfect.


Hey @emilengler 

I just took a glimpse at their current website. Damn, it seems as the old download API isn't available anymore. Currently, it seems the package-per-distribution view of the dataset can only be obtained by the HTML file they serve.

The autocomplete API however is available, for example like this:
https://api.pkgs.org/packages/autocomplete/101/binutils

They also offer an API for all distributions they support: https://api.pkgs.org/packages/distros/
(So, in theory, when they offer an additional API for packages themselves, it could be mapped easily).

But I guess that the autocomplete API actually could be enough for this use case. If you have e.g. the response JSON for `binutils` you could iterate over the resulting names and ask the package manager for whether or not that package exists (like `pacman -Si binutils` or `apt-cache show binutils`) - or am I missing something?

**Comment by cvengler** [comment]
We should ask them to offer an API.
My problem with a 3rd party API is that we are depend on their service.
Anyway I will ask them to offer an API

**Comment by cvengler** [comment]
I've just wrote Mykola Ulianytskyi (the author of the site) an E-Mail. I will let you know if there are any updates regarding the request.

**Comment by apatrascu** [comment]
@cookiengineer and @emilengler  I was wondering how do you expect the fuzzy search to work in case you want a more tricky library (`binutils` is simple to autodetect, just like `htop`, etc is). 

E.g. searching for `libcurl` on Ubuntu, you get `["libcurl-ocaml", "libcurl-ocaml-dev", "libcurl3", "libcurl3-gnutls", "libcurl3-nss", "libcurl4-doc", "libcurl4-gnutls-dev", "libcurl4-nss-dev", "libcurl4-openssl-dev", "libcurlpp-dev", "libcurlpp0"]` as response. 

Even if you have an API from pkgs.org, how would the fuzzy searcher know which one do you want, since you cannot install all of them?

**Comment by cookiengineer** [comment]
@apatrascu I would probably calculate the minimum [levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) to the input and output a suggestion with a confirmation for the user (sorted by min-to-max distance so it reflects the statistical likeliness).

So for example if you want libcurl you just install "libcurl" or "curl", whereas when you use "libcurl ocaml" or "curl ocaml" it will result in the libcurl-ocaml bindings due to the levenshtein distance.

**Comment by apatrascu** [comment]
@cookiengineer this would mean that the user will need to give extra details about what he or she wants. E.g. to install the `licurl4-nss-dev` you would have to write something like `"libcurl4 nss dev"` to make sure you get the correct package. How is this different than writing the full package name for each distro? 

I think the whole point of this issue (and a valid one, which I'm interested in also) is to abstract as much as possible the package name from the user and let the tool automagically find the proper one. Please correct me if I'm wrong.

**Comment by cookiengineer** [comment]
>  How is this different than writing the full package name for each distro?

You are assuming that every distribution has the identical naming scheme. They have not. And sth. like "curl nss dev" would suffice, too.

**Comment by ghost** [comment]
Also i dont think we need some online database, apt and other package managers do this for you.

So we would need to find a library in C++ for each package manager that returns all packages in an array

**Comment by cvengler** [comment]
I think I can close this now.
If not, please tell me
