### ISSUE TITLE
Does not compile in os x mojave with only commandline tools installed

### ISSUE THREAD

**Issue by gizmomogwai** [emilengler/sysget#6]
adding
```
-std=c++11
```
helps.

**Comment by cvengler** [comment]
Thank you for your issue.
Can you please post the full command instead of `-std=c++11` ?

**Comment by gizmomogwai** [comment]
i added this flag to all g++ calls in the makefile.
e.g.
```
FLAGS=-std=c++11
prog: main.o search.o utils.o install.o remove.o update.o clean.o
        g++ $(FLAGS) -o sysget.o main.o search.o utils.o install.o remove.o update.o clean.o

main.o: main.cpp
        g++ $(FLAGS) -c main.cpp

utils.o: utils.h utils.cpp
        g++ $(FLAGS) -c utils.h utils.cpp

search.o: search.h search.cpp
        g++ $(FLAGS) -c search.h search.cpp
        
install.o: install.h install.cpp
        g++ $(FLAGS) -c install.h install.cpp

remove.o: remove.h remove.cpp
        g++ $(FLAGS) -c remove.h remove.cpp

update.o: update.h update.cpp
        g++ $(FLAGS) -c update.h update.cpp

clean.o: clean.h clean.cpp
        g++ $(FLAGS) -c clean.h clean.cpp
```

**Comment by cvengler** [comment]
Thank you, I will create a makefile for MacOS

**Comment by gizmomogwai** [comment]
actually the feature you are using, is requiring a "modern" c++ standard. i wonder why it compiles on other targets?

**Comment by cvengler** [comment]
Thank you for your sugestion I've just added it

**Comment by cvengler** [comment]
https://github.com/emilengler/sysget/commit/c99ece1f27007da688e05ae24cce5680e938fc94

**Comment by gizmomogwai** [comment]
you know that you can auto-close and link issues by adding e.g. Closes #6 to the git commit message?
as described here:
https://help.github.com/articles/closing-issues-using-keywords/

**Comment by cvengler** [comment]
Now I know it ;)
Sorry I hope the credit in the comment of the commit is enough.
I will keep this in mind when closing issues in the future.
Anyway, thank you for telling me about this nice feature.

**Comment by gizmomogwai** [comment]
no problem ... i was just wondering :)
keep up the good work, i really like the idea of sysget ...
