### ISSUE TITLE
wrong error message in os x if /usr/local/share/sysget does not exist

### ISSUE THREAD

**Issue by gizmomogwai** [emilengler/sysget#7]
it complains like this:
```
Unable to create config, are you root ?
```
even when running the command as sudo (which should not be needed).

**Comment by cvengler** [comment]
Hi gizmomogwai,
First open a terminal as a root user.
Otherwise you can use the sudo command

Please try:
`sudo mkdir -p /usr/local/share/sysget`
Try to restart the program then.
If the error message still occurse try to execute sysget as root
`sudo sysget`

Please reply if it works :)

**Comment by gizmomogwai** [comment]
i can also create the folder as a non root user, after this, sysget runs even without sudo.
thanks for the quick reply. i still think, that the error message is misleading .. or that sysget should ensure the folder to exist, with the proper access rights.

**Comment by cvengler** [comment]
The error message is being created by the `create_conf` function inside `utils.cpp`.
The error message occurse if sysget cannot write to the file so I think it is not misleading.
Can you please try it as a root user ?

**Comment by gizmomogwai** [comment]
the problem is, if the folder is not there, the function cannot write the file as well.
if the folder is there, all is good ... create_conf does not even try to create a folder.

**Comment by gizmomogwai** [comment]
see also e.g. https://stackoverflow.com/questions/18682148/how-to-create-directories-automatically-using-ofstream

**Comment by cvengler** [comment]
Thank you, I will patch this
