### ISSUE TITLE
missing chocolatey

### ISSUE THREAD

**Issue by fiendish** [emilengler/sysget#8]
https://www.chocolatey.org

**Comment by neeasade** [comment]
If that's in the running I'd also like to plug https://scoop.sh

**Comment by cvengler** [comment]
sysget will never get chocolatey.
The reason behind this is that sysget is Unix only.
Maybe their will be a sysget-windows version in the future.
However thank you for this suggestion

**Comment by fiendish** [comment]
> sysget is Unix only

Uh. What? Then you need to update your readme, because it says "sysget is a bridge that lets you use one syntax to every package manager on *every* operating system."

**Comment by cvengler** [comment]
Sorry for being a bit too harsh.
I will update the README of course.
With every operating system I meant every Linux distribution (including macOS).
However I will probably do a windows version of sysget.
Thank you
